// <auto-generated />
using System.Collections.Generic;
using EFDemoConsoleApp1.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDemoConsoleApp1.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20260529064302_TPT")]
    partial class TPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "EFDemoConsoleApp1.Entities.Employee.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Area")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line1")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Pincode")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("EmpId");

                    b.HasIndex("ProjectID");

                    b.ToTable("tbl_emp");
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectID"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("EmployeeSkill", b =>
                {
                    b.Property<int>("EmployeesEmpId")
                        .HasColumnType("int");

                    b.Property<int>("SkillsSkillID")
                        .HasColumnType("int");

                    b.HasKey("EmployeesEmpId", "SkillsSkillID");

                    b.HasIndex("SkillsSkillID");

                    b.ToTable("EmployeeSkill");
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.DesktopProject", b =>
                {
                    b.HasBaseType("EFDemoConsoleApp1.Entities.Project");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DesktopProjects");
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.MobileProject", b =>
                {
                    b.HasBaseType("EFDemoConsoleApp1.Entities.Project");

                    b.Property<string>("Plotform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MobileProjects");
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.WebProject", b =>
                {
                    b.HasBaseType("EFDemoConsoleApp1.Entities.Project");

                    b.Property<string>("WebUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("WebProjects");
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.Employee", b =>
                {
                    b.HasOne("EFDemoConsoleApp1.Entities.Project", "Project")
                        .WithMany("Employees")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("EmployeeSkill", b =>
                {
                    b.HasOne("EFDemoConsoleApp1.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesEmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFDemoConsoleApp1.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsSkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.DesktopProject", b =>
                {
                    b.HasOne("EFDemoConsoleApp1.Entities.Project", null)
                        .WithOne()
                        .HasForeignKey("EFDemoConsoleApp1.Entities.DesktopProject", "ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.MobileProject", b =>
                {
                    b.HasOne("EFDemoConsoleApp1.Entities.Project", null)
                        .WithOne()
                        .HasForeignKey("EFDemoConsoleApp1.Entities.MobileProject", "ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.WebProject", b =>
                {
                    b.HasOne("EFDemoConsoleApp1.Entities.Project", null)
                        .WithOne()
                        .HasForeignKey("EFDemoConsoleApp1.Entities.WebProject", "ProjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EFDemoConsoleApp1.Entities.Project", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
